import type { RuleSetData } from "./types";

// Rules transcribed from the hidden "Calculo" sheet of Cotizador PRO V6R02-2026.xlsm.
// SAP codes only — prices always come from the active price list.
export const DEFAULT_RULES: RuleSetData = {
  systems: [
    {
      key: "PERIMETRAL",
      name: "CercasPro Perimetral",
      tagline: "Paneles electrosoldados con postes de 60×60 a 100×100 mm para cerramientos de terrenos, fábricas y urbanizaciones.",
      coating: "Dúplex (galvanizado + poliéster)",
      finish: "Verde",
      image: "/img/perimetral.webp",
      active: true,
      options: { placa: true, puas: true, inclinacion: true },
      heights: [
        {
          value: 1.11,
          label: "1,11 m",
          params: { panel1: "189168", panel2: null, postePlinto: "270873", postePlaca: "270872", tapa: "189488", perno: "270501", brazo: "189186", fijPorPoste: 3, permitePlaca: true, permitePuas: false },
        },
        {
          value: 2.08,
          label: "2,08 m",
          params: { panel1: "189483", panel2: null, postePlinto: "270876", postePlaca: "270874", tapa: "189488", perno: "270501", brazo: "189186", fijPorPoste: 5, permitePlaca: true, permitePuas: true },
        },
        {
          value: 2.4,
          label: "2,40 m",
          params: { panel1: "273709", panel2: null, postePlinto: "270526", postePlaca: "665190", tapa: "189197", perno: "270502", brazo: "270512", fijPorPoste: 5, permitePlaca: true, permitePuas: true },
        },
        {
          value: 3.05,
          label: "3,05 m (1,11 + 2,08)",
          params: { panel1: "189168", panel2: "189483", postePlinto: "270527", postePlaca: null, tapa: "189197", perno: "270502", brazo: "270512", fijPorPoste: 7, permitePlaca: false, permitePuas: true },
        },
        {
          value: 4.02,
          label: "4,02 m (2,08 + 2,08)",
          params: { panel1: "189483", panel2: "189483", postePlinto: "270877", postePlaca: null, tapa: "189196", perno: "270503", brazo: "270512", fijPorPoste: 9, permitePlaca: false, permitePuas: true },
        },
      ],
      variables: [
        { name: "tramos", label: "Tramos", expr: "roundup(L / 2.5 * (1 + incl))" },
        { name: "postes", label: "Postes", expr: "tramos + 1" },
        { name: "paneles", label: "Paneles", expr: "roundup(L / 2.5)" },
        { name: "conPuas", label: "Lleva púas", expr: "puas && permitePuas" },
        { name: "fijaciones", label: "Fijaciones", expr: "postes * fijPorPoste" },
        { name: "pernos", label: "Pernos y tuercas", expr: "fijaciones + (conPuas ? postes : 0)" },
        { name: "brazos", label: "Brazos para púas", expr: "conPuas ? postes : 0" },
        { name: "metrosPuas", label: "Metros de alambre de púas (3 hileras)", expr: "conPuas ? L * 3 : 0" },
      ],
      lines: [
        { id: "poste", label: "Poste", section: "principal", kind: "product", sku: "placa ? postePlaca : postePlinto", qty: "postes", pricing: "tier" },
        { id: "tapa", label: "Tapa de poste", section: "principal", kind: "product", sku: "tapa", qty: "postes", pricing: "tier" },
        { id: "fijacion", label: "Fijación", section: "principal", kind: "product", sku: "'272173'", qty: "fijaciones", pricing: "tier" },
        { id: "perno", label: "Perno coche INOX", section: "principal", kind: "product", sku: "perno", qty: "pernos", pricing: "tier" },
        { id: "tuerca", label: "Tuerca autorrompiente", section: "principal", kind: "product", sku: "'270504'", qty: "pernos", pricing: "tier" },
        { id: "panel_inferior", label: "Panel", section: "principal", kind: "product", sku: "panel1", qty: "paneles", pricing: "tier" },
        { id: "panel_superior", label: "Panel superior", section: "principal", kind: "product", sku: "panel2", qty: "paneles", when: "panel2 != ''", pricing: "tier" },
        { id: "perno_anclaje", label: "Perno de anclaje (4 por poste)", section: "principal", kind: "product", sku: "'189489'", qty: "postes * 4", when: "placa", pricing: "tier" },
        { id: "brazo", label: "Brazo para púas", section: "principal", kind: "product", sku: "brazo", qty: "brazos", when: "conPuas", pricing: "tier" },
        { id: "fijacion_jumbo", label: "Fijación Jumbo (3 por brazo)", section: "principal", kind: "product", sku: "'189162'", qty: "brazos * 3", when: "conPuas", pricing: "tier" },
        { id: "spray_verde", label: "Spray verde de retoque", section: "adicionales", kind: "product", sku: "'189205'", qty: "L < 25 ? 1 : roundup(L / 25)", pricing: "tier" },
        { id: "spray_galv", label: "Spray galvanizado en frío", section: "adicionales", kind: "product", sku: "'683471'", qty: "L < 50 ? 1 : roundup(L / 100)", pricing: "tier" },
        {
          id: "alambre_puas",
          label: "Alambre de púas Motto (rollos)",
          section: "adicionales",
          kind: "rolls",
          meters: "metrosPuas",
          when: "conPuas",
          pricing: "livianos",
          rolls: [
            { meters: 500, sku: "188057" },
            { meters: 400, sku: "188055" },
            { meters: 300, sku: "188051" },
            { meters: 200, sku: "188053" },
          ],
        },
      ],
      checks: [
        { when: "placa && !permitePlaca", level: "error", message: "La altura {altura} m no se dispone con poste de placa. Elige poste con plinto." },
        { when: "puas && !permitePuas", level: "warning", message: "La opción con púas no aplica para {altura} m; se cotiza sin púas." },
      ],
    },
    {
      key: "URBANA",
      name: "CercasPro Urbana",
      tagline: "Panel de 2,08 m con poste rectangular 60×40 mm, ideal para conjuntos residenciales y áreas urbanas.",
      coating: "Dúplex (galvanizado + poliéster)",
      finish: "Verde",
      image: "/img/urbana.webp",
      active: true,
      options: { placa: false, puas: true, inclinacion: true },
      heights: [
        {
          value: 2.08,
          label: "2,08 m",
          params: { panel: "667701", poste: "667702", tapa: "667705", fijacion: "667706", perno: "270502", brazo: "689168", fijPorPoste: 5, permitePuas: true },
        },
      ],
      variables: [
        { name: "tramos", label: "Tramos", expr: "roundup(L / 2.5 * (1 + incl))" },
        { name: "postes", label: "Postes", expr: "tramos + 1" },
        { name: "paneles", label: "Paneles", expr: "roundup(L / 2.5)" },
        { name: "conPuas", label: "Lleva púas", expr: "puas && permitePuas" },
        { name: "fijaciones", label: "Fijaciones", expr: "postes * fijPorPoste" },
        { name: "pernos", label: "Pernos y tuercas", expr: "fijaciones" },
      ],
      lines: [
        { id: "poste", label: "Poste", section: "principal", kind: "product", sku: "poste", qty: "postes", pricing: "tier" },
        { id: "tapa", label: "Tapa de poste", section: "principal", kind: "product", sku: "tapa", qty: "postes", pricing: "tier" },
        { id: "fijacion", label: "Fijación", section: "principal", kind: "product", sku: "fijacion", qty: "fijaciones", pricing: "tier" },
        { id: "perno", label: "Perno coche INOX", section: "principal", kind: "product", sku: "perno", qty: "pernos", pricing: "tier" },
        { id: "tuerca", label: "Tuerca autorrompiente", section: "principal", kind: "product", sku: "'270504'", qty: "pernos", pricing: "tier" },
        { id: "panel", label: "Panel", section: "principal", kind: "product", sku: "panel", qty: "paneles", pricing: "tier" },
        { id: "brazo", label: "Brazo para púas inclinado", section: "principal", kind: "product", sku: "brazo", qty: "postes", when: "conPuas", pricing: "tier" },
        { id: "spray_verde", label: "Spray verde de retoque", section: "adicionales", kind: "product", sku: "'189205'", qty: "L < 25 ? 1 : roundup(L / 25)", pricing: "tier" },
        { id: "spray_galv", label: "Spray galvanizado en frío", section: "adicionales", kind: "product", sku: "'683471'", qty: "L < 50 ? 1 : roundup(L / 100)", pricing: "tier" },
      ],
      checks: [],
    },
    {
      key: "INTRADOMICILIARIA",
      name: "CercasPro Intradomiciliaria",
      tagline: "Kit liviano de 1,25 m para jardines, patios y delimitación interna. Incluye kit de puerta.",
      coating: "Dúplex (galvanizado + poliéster)",
      finish: "Verde",
      image: "/img/intradomiciliaria.webp",
      active: true,
      options: { placa: false, puas: false, inclinacion: false },
      heights: [
        { value: 1.25, label: "1,25 m", params: { panel: "270428", kitPoste: "270430", kitPuerta: "270433", puertas: 1 } },
      ],
      variables: [
        { name: "paneles", label: "Paneles", expr: "roundup(L / 1.5)" },
        { name: "postes", label: "Kits de poste", expr: "paneles + 1" },
      ],
      lines: [
        { id: "panel", label: "Panel", section: "principal", kind: "product", sku: "panel", qty: "paneles", pricing: "tier" },
        { id: "kit_poste", label: "Kit de poste", section: "principal", kind: "product", sku: "kitPoste", qty: "postes", pricing: "tier" },
        { id: "kit_puerta", label: "Kit de puerta", section: "principal", kind: "product", sku: "kitPuerta", qty: "puertas", pricing: "tier" },
        { id: "spray_verde", label: "Spray verde de retoque", section: "adicionales", kind: "product", sku: "'189205'", qty: "L < 25 ? 1 : roundup(L / 25)", pricing: "tier" },
      ],
      checks: [],
    },
    {
      key: "MAXIMA_SEGURIDAD",
      name: "CercasPro Máxima Seguridad",
      tagline: "Malla de alta densidad anti-escalada con poste 100×50 mm, para instalaciones críticas.",
      coating: "Dúplex (galvanizado + poliéster)",
      finish: "Gris",
      image: "/img/maxima-seguridad.webp",
      active: true,
      options: { placa: false, puas: false, inclinacion: true },
      heights: [
        { value: 2.1, label: "2,10 m", params: { panel: "270434", poste: "270437" } },
        { value: 2.45, label: "2,45 m", params: { panel: "270435", poste: "270438" } },
        { value: 3, label: "3,00 m", params: { panel: "270436", poste: "270439" } },
      ],
      variables: [
        { name: "tramos", label: "Tramos", expr: "roundup(L / 2.4)" },
        { name: "paneles", label: "Paneles", expr: "roundup(L / 2.4)" },
        { name: "postes", label: "Postes", expr: "round((tramos + 1) * (1 + incl))" },
        { name: "fijaciones", label: "Fijaciones (8 por poste)", expr: "postes * 8" },
        { name: "pernos", label: "Pernos y tuercas", expr: "fijaciones" },
      ],
      lines: [
        { id: "poste", label: "Kit de poste", section: "principal", kind: "product", sku: "poste", qty: "postes", pricing: "tier" },
        { id: "tapa", label: "Tapa PVC", section: "principal", kind: "product", sku: "'270440'", qty: "postes", pricing: "tier" },
        { id: "panel", label: "Panel", section: "principal", kind: "product", sku: "panel", qty: "paneles", pricing: "tier" },
        { id: "fijacion", label: "Fijación", section: "principal", kind: "product", sku: "'645392'", qty: "fijaciones", pricing: "tier" },
        { id: "perno", label: "Perno coche INOX 1/4\"×5\"", section: "principal", kind: "product", sku: "'645393'", qty: "pernos", pricing: "tier" },
        { id: "tuerca", label: "Tuerca autorrompiente", section: "principal", kind: "product", sku: "'270504'", qty: "pernos", pricing: "tier" },
        { id: "spray_galv", label: "Spray galvanizado en frío", section: "adicionales", kind: "product", sku: "'683471'", qty: "L < 50 ? 1 : roundup(L / 100)", pricing: "tier" },
      ],
      checks: [],
    },
  ],
};
